<a href="https://colab.research.google.com/github/imrankhanjoya/algotrading/blob/main/travel.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
#MACD indictor for trading 
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [65]:
data = []
inLot = []
i=0
lot = 0.02
lotStart = 0.02
lotIn = 2
gap = 100
while i < 2000:
  data.insert(i,i*gap)
  lotStart = lotStart*1 
  inLot.insert(i,lotStart)
  i = i + 1

inLot

df = pd.DataFrame(data, columns = ['Gap'])
df["Lot"] = lot
#df["lotIn"] = np.cumsum(df["lotIn"]) * lotIn
df["LotSum"] = np.cumsum(df["Lot"])
df["lotIn"] = lotStart
#df["lotIn"] = np.cumsum(df["lotIn"])
df["lotIn"] = df["lotIn"].shift(-1) * 2
df["GapSum"] = np.cumsum(df["Gap"])
df["TradeLoss"] = df["GapSum"] * lot 




df.head(50)

     Gap   Lot  LotSum  lotIn  GapSum  TradeLoss
0      0  0.02    0.02   0.04       0        0.0
1    100  0.02    0.04   0.04     100        2.0
2    200  0.02    0.06   0.04     300        6.0
3    300  0.02    0.08   0.04     600       12.0
4    400  0.02    0.10   0.04    1000       20.0
5    500  0.02    0.12   0.04    1500       30.0
6    600  0.02    0.14   0.04    2100       42.0
7    700  0.02    0.16   0.04    2800       56.0
8    800  0.02    0.18   0.04    3600       72.0
9    900  0.02    0.20   0.04    4500       90.0
10  1000  0.02    0.22   0.04    5500      110.0
11  1100  0.02    0.24   0.04    6600      132.0
12  1200  0.02    0.26   0.04    7800      156.0
13  1300  0.02    0.28   0.04    9100      182.0
14  1400  0.02    0.30   0.04   10500      210.0
15  1500  0.02    0.32   0.04   12000      240.0
16  1600  0.02    0.34   0.04   13600      272.0
17  1700  0.02    0.36   0.04   15300      306.0
18  1800  0.02    0.38   0.04   17100      342.0
19  1900  0.02    0.40   0.04   19000      380.0
20  2000  0.02    0.42   0.04   21000      420.0
21  2100  0.02    0.44   0.04   23100      462.0
22  2200  0.02    0.46   0.04   25300      506.0
23  2300  0.02    0.48   0.04   27600      552.0
24  2400  0.02    0.50   0.04   30000      600.0
25  2500  0.02    0.52   0.04   32500      650.0
26  2600  0.02    0.54   0.04   35100      702.0
27  2700  0.02    0.56   0.04   37800      756.0
28  2800  0.02    0.58   0.04   40600      812.0
29  2900  0.02    0.60   0.04   43500      870.0
30  3000  0.02    0.62   0.04   46500      930.0
31  3100  0.02    0.64   0.04   49600      992.0
32  3200  0.02    0.66   0.04   52800     1056.0
33  3300  0.02    0.68   0.04   56100     1122.0
34  3400  0.02    0.70   0.04   59500     1190.0
35  3500  0.02    0.72   0.04   63000     1260.0
36  3600  0.02    0.74   0.04   66600     1332.0
37  3700  0.02    0.76   0.04   70300     1406.0
38  3800  0.02    0.78   0.04   74100     1482.0
39  3900  0.02    0.80   0.04   78000     1560.0
40  4000  0.02    0.82   0.04   82000     1640.0
41  4100  0.02    0.84   0.04   86100     1722.0
42  4200  0.02    0.86   0.04   90300     1806.0
43  4300  0.02    0.88   0.04   94600     1892.0
44  4400  0.02    0.90   0.04   99000     1980.0
45  4500  0.02    0.92   0.04  103500     2070.0
46  4600  0.02    0.94   0.04  108100     2162.0
47  4700  0.02    0.96   0.04  112800     2256.0
48  4800  0.02    0.98   0.04  117600     2352.0
49  4900  0.02    1.00   0.04  122500     2450.0